### ISSUE TITLE
Genesis time change each run

### ISSUE THREAD

**Issue by trungdlp-wolffun** [ethpandaops/ansible-collection-general#206]
Let's to review: https://github.com/ethpandaops/ansible-collection-general/blob/master/roles/generate_kubernetes_config/templates/forky.yaml.j2#L43

**Comment by barnabasbusa** [comment]
Genesis time is supposed to change each run, unless you hardcode the values. 

This will generate the correct timestamp for each genesis run.

**Comment by trungdlp-wolffun** [comment]
@barnabasbusa I think genesis time should follow random seed.

**Comment by barnabasbusa** [comment]
Random seed will lead to random genesis time? Which can lead to a genesis time that is in the past. 

What exactly is your issue? You can hardcode the genesis time to a specific epoch time, if you want to have a predictable outcome.

**Comment by trungdlp-wolffun** [comment]
Thank for your help :P
