### ISSUE TITLE
Add BONSAI as the default storage engine for besu

### ISSUE THREAD

**Issue by parithosh** [ethpandaops/ansible-collection-general#58]
`--data-storage-format=BONSAI`, besu will probably update their default in a future release but we should be using bonsai as our default

**Comment by skylenet** [comment]
IMO, we should keep whatever besu decides as their default. So I wouldn't bake this into the defaults, but instead add it as an extra arg on whatever deployments we need it.

**Comment by parithosh** [comment]
Besu said they wanted to change the default and didn't get to it so far, so in the devs opinion this should've been the "Default" all along. Main reason to add it here is that we then don't have to think about it for each and every testnet.

**Comment by barnabasbusa** [comment]
+1 to change the default to Bonsai. Caused too much trouble already when we did not use Bonsai.

**Comment by barnabasbusa** [comment]
BONSAI is now default on Besu
