### ISSUE TITLE
Fix fail2ban issue

### ISSUE THREAD

**Issue by parithosh** [ethpandaops/ansible-collection-general#63]
on init setup, fail2ban blocks the deployer IP. Need to find a way around it.

**Comment by skylenet** [comment]
This problem mainly happens on initial setup of a server, the reason for that is that the "boostrap_user", in our case "devops" doesn't exist yet, but ansible tries to connect using it. This will generate some failed SSH connections from our local IP address, therefore having fail2ban banning that IP once it's started. 

Adding the IP of the ansible controller to the ignore list, should be a good workaround for this problem: https://github.com/ethpandaops/4844-testnet/pull/92
