### ISSUE TITLE
Shared ssh key to create machines

### ISSUE THREAD

**Issue by barnabasbusa** [ethpandaops/ansible-collection-general#73]
When used a shared ssh key to create a new infra, the ansible script will work till the point of root login is disabled.

Workaround would be to create a new user e.g: ethpandaops and add the shared ssh key as its pubkey, and add ethpandaops github user as a member whose keys will always be present on all our machines.

**Comment by skylenet** [comment]
Added the shared key to authorized_keys ( See 4844 testnet repo ). That should be enough.
