### ISSUE TITLE
ethereumjs docker stop timeout issue

### ISSUE THREAD

**Issue by barnabasbusa** [ethpandaops/ansible-collection-general#86]
Sometimes, due to the inefficiencies of ethereumjs, it cannot stop within 15 seconds (http current timeout).
Error message:
```
UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=15)
```
Workaround solution is mentioned in this issue: https://github.com/docker/compose/issues/3927

TLDR we should set: 
```
export DOCKER_CLIENT_TIMEOUT=120
export COMPOSE_HTTP_TIMEOUT=120
```

**Comment by parithosh** [comment]
I guess the related flag for the ansible module is one of these: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-removal_wait_timeout

https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-stop_timeout

or probably change the generic timeout: 
https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-timeout

**Comment by skylenet** [comment]
fix in here: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2899

**Comment by skylenet** [comment]
Is this still a problem @barnabasbusa ? I think we can close thise one.

**Comment by barnabasbusa** [comment]
Lets close it for now, and reopen/restart a new issue if we still notice this issue.
